[profile.default]
src = "src"
out = "foundry/out"
libs = ["node_modules", "foundry/lib"]
cache_path = "foundry/cache"
test = "foundry/test"
optimizer = true
optimizer_runs = 200
evm_version = "london"

[profile.default.fuzz]
runs = 250

[profile.default.invariant]
runs = 250
depth = 20

[profile.ci.fuzz]
runs = 10000

[profile.ci.invariant]
runs = 10000
depth = 50